# -*- coding: utf-8 -*-
"""California housing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q77Za5BMbztVHKPuecIz_tp8RdFaY6lN

Description du jeu de données California Housing

https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html

Le jeu de données California Housing contient les caractéristiques suivantes pour chaque échantillon de données :

    MedInc: Revenu médian des ménages dans le quartier (en dizaines de milliers de dollars).
    HouseAge: Âge médian des maisons dans le quartier.
    AveRooms: Nombre moyen de pièces par logement.
    AveBedrms: Nombre moyen de chambres à coucher par logement.
    Population: Population totale du quartier.
    AveOccup: Moyenne des occupants par logement.
    Latitude: Latitude du quartier.
    Longitude: Longitude du quartier.

Variable cible

La variable cible (ou variable à prédire) est :

    MedHouseVal: Valeur médiane des maisons dans le quartier (en centaines de milliers de dollars).
"""

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/SkatAI/deeplearning/master/data/housing.csv')
df.head()

